### ISSUE TITLE
US08 - Histórico de empréstimo de usuários

### ISSUE THREAD

**Issue by mateusmaiamaia** [fga-eps-mds/2024.2-LIVRO-LIVRE-DOC#66]
Eu, como Camilla Marques, desejo consultar o histórico de empréstimos de um usuário específico, para monitorar a frequência de empréstimos.

## Tarefas
- [ ]  Criar uma tela no sistema para exibir o histórico de todos os livros que tal usuário pegou.
- [ ]  Recuperar os dados de empréstimos do banco de dados para o administrador.
- [ ]  Implementar funcionalidade de ordenação dos empréstimos por data.
- [ ] Exibir o histórico em formato de Grid com as informações pertinentes.
- [ ] Exibir se o usuário está em posse de algum livro e, se sim, qual.

## Critérios de Aceitação
- [ ] O sistema deve exibir o histórico completo de empréstimos do usuário.
- [ ] O administrador deve poder ordenar os empréstimos por data, de forma crescente ou decrescente.
- [ ] Para o histórico do usuário, as informações exibidas devem incluir:
    - [ ] Capa dos livros
    - [ ] Título dos livros
    - [ ] Todos os livros
    - [ ] Todas as datas de Empréstimo
    - [ ] Todas as datas de Devolução
        - [ ] Caso o livro tenha sido devolvido, a data de devolução será exibida.
        - [ ] Caso o livro não tenha sido devolvido, a data de devolução será marcada como "Em posse de ...".
        - [ ] "Em posse" caso o livro não tenha sido devolvido.
        - [ ] "Devolvido" caso o livro tenha sido devolvido.
- [ ] O histórico deve ser apresentado em formato de Grid, com cada linha representando um empréstimo.
- [ ] Deve ser possível navegar entre as páginas utilizando controles de paginação (como botões "Próximo", "Anterior" e números de páginas).
- [ ] O sistema de pesquisa deverá exibir os resultados paginados, apresentando até 20 livros por página.
- [ ] Os filtros disponíveis para pesquisa no histórico de empréstimos do usuário são:
    - [ ] Por Data: permite selecionar um intervalo de datas específico para localizar registros.
    - [ ] Por Livro: Identifica o estado atual do livro, indentificar se tal usuário já teve contato com o livro.
    - [ ] Por Duração do Empréstimo: Ajuda a filtrar registros com base no tempo total de empréstimo, como curto, médio ou longo prazo.

## Protótipo

link:
[https://www.figma.com/design/edZfZi6v6sV8lmFCfGCMPW/Livro-Livre?node-id=172-5&p=f&t=Ihjjfg1JCczToBCG-0](https://www.figma.com/design/edZfZi6v6sV8lmFCfGCMPW/Livro-Livre?node-id=591-61&p=f&t=Ihjjfg1JCczToBCG-0)
